branches:
  only:
  - master

language: go
cache:
  directories:
  - $HOME/.cache/go-build
  - $GOPATH/pkg/mod
go:
- tip
- 1.13.x
install: true
script:
- go vet ./...
- go test -race ./...

jobs:
  include:
  - name: macOS
    os: osx
    osx_image: xcode11.2
    language: go
    go: 1.13.x
  - name: Windows
    os: windows
    language: go
    go: 1.13.x
